const groups = [
	{
		properties: ['all'],
	},
	{
		groupName: 'position',
		properties: [
			'position',
			'top',
			'right',
			'bottom',
			'left',
			'inset',
			'inset-block',
			'inset-block-start',
			'inset-block-end',
			'inset-inline',
			'inset-inline-start',
			'inset-inline-end',
		],
	},
	{
		groupName: 'Display',
		properties: ['box-sizing', 'display'],
	},
	{
		groupName: 'Grid',
		properties: [
			'grid',
			'grid-area',
			'grid-auto-rows',
			'grid-row',
			'grid-row-start',
			'grid-row-end',
			'grid-auto-columns',
			'grid-column',
			'grid-column-start',
			'grid-column-end',
			'grid-template',
			'grid-template-areas',
			'grid-template-rows',
			'grid-template-columns',
		],
	},
	{
		groupName: 'Flex',
		properties: [
			'flex',
			'flex-basis',
			'flex-direction',
			'flex-flow',
			'flex-grow',
			'flex-shrink',
			'flex-wrap',
		],
	},
	{
		groupName: 'Layout',
		properties: [
			'align-content',
			'align-items',
			'align-self',
			'justify-content',
			'justify-items',
			'justify-self',
			'gap',
			'row-gap',
			'column-gap',
			'order',
			'float',
			'margin',
			'margin-top',
			'margin-right',
			'margin-bottom',
			'margin-left',
			'margin-block-start',
			'margin-block-end',
			'margin-inline-start',
			'margin-inline-end',
			'padding',
			'padding-top',
			'padding-right',
			'padding-bottom',
			'padding-left',
			'padding-block-start',
			'padding-block-end',
			'padding-inline-start',
			'padding-inline-end',
			'width',
			'min-width',
			'max-width',
			'height',
			'min-height',
			'max-height',
			'overflow',
			'overflow-x',
			'overflow-y',
		],
	},
	{
		groupName: 'Decoration',
		properties: [
			'background',
			'background-color',
			'background-image',
			'background-position',
			'background-position-x',
			'background-position-y',
			'background-size',
			'background-clip',
			'background-origin',
			'background-attachment',
			'background-repeat',
			'background-blend-mode',

			'border',
			'border-width',
			'border-style',
			'border-color',
			'border-top',
			'border-top-width',
			'border-top-style',
			'border-top-color',
			'border-bottom',
			'border-bottom-width',
			'border-bottom-style',
			'border-bottom-color',
			'border-left',
			'border-left-width',
			'border-left-style',
			'border-left-color',
			'border-right',
			'border-right-width',
			'border-right-style',
			'border-right-color',
			'border-radius',
			'border-top-left-radius',
			'border-top-right-radius',
			'border-bottom-right-radius',
			'border-bottom-left-radius',
			'border-start-start-radius',
			'border-start-end-radius',
			'border-end-end-radius',
			'border-end-start-radius',
			'border-collapse',
			'outline',
			'outline-width',
			'outline-style',
			'outline-color',
			'outline-offset',
		],
	},
	{
		groupName: 'Typography',
		properties: [
			'font',
			'font-family',
			'font-size',
			'font-weight',
			'font-style',
			'color',
			'line-height',
			'letter-spacing',
			'text-align',
			'text-decoration',
			'text-transform',
			'text-overflow',
			'list-style',
			'list-style-position',
			'list-style-type',
			'list-style-image',
		],
	},
];

module.exports = groups;
